name = "family-calendar-api"
main = "src/index.js"
compatibility_date = "2026-02-12"

[[d1_databases]]
binding = "DB"
database_name = "family_calendar_db"
database_id = "23f53ecb-bb0d-41ae-8bc9-3e3966274af5"

[vars]
# Your Pages URL (or custom domain) for CORS:
FRONTEND_ORIGIN = "https://cal.sndjy.us"

# Used to sign session JWTs (make it long and random)
JWT_SECRET = "saidtoreplacewithalongrandomstringsoijustthoughtaboutthis"

# One-time bootstrap token to create your first user (admin).
# Keep it secret. After you create your account, you can change it or ignore it.
BOOTSTRAP_TOKEN = "joeyisawesome"
